# Generated by Django 5.2.12 on 2026-03-10 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True, verbose_name='Kino Kodi')),
                ('title', models.CharField(max_length=255, verbose_name='Kino Nomi')),
                ('message_id', models.IntegerField(verbose_name='Xabar ID (Kanalda)')),
                ('channel_id', models.BigIntegerField(blank=True, null=True, verbose_name="Kanal ID (Agar alohida bo'lsa)")),
                ('views', models.IntegerField(default=0, verbose_name="Ko'rishlar soni")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan sana")),
            ],
            options={
                'verbose_name': 'Kino',
                'verbose_name_plural': 'Kinolar',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('telegram', 'Telegram'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('other', 'Boshqa')], default='telegram', max_length=50, verbose_name='Platforma')),
                ('name', models.CharField(max_length=255, verbose_name='Vazifa nomi')),
                ('url', models.URLField(verbose_name='Havola (URL)')),
                ('chat_id', models.CharField(blank=True, help_text='Telegram obunani tekshirish uchun kanal username yoki ID (Masalan: @kanal_nomi yoki -100...)', max_length=255, null=True, verbose_name='Kanal ID/Username')),
                ('reward', models.IntegerField(default=1, verbose_name='Mukofot (Tanga)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
            ],
            options={
                'verbose_name': 'Vazifa',
                'verbose_name_plural': 'Vazifalar',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Username')),
                ('coins', models.IntegerField(default=0, verbose_name='Tangalar')),
                ('last_bonus_date', models.DateField(blank=True, null=True, verbose_name='Oxirgi bonus sanasi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan sana")),
                ('referrer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='bot_app.user', verbose_name='Taklif qilgan')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Miqdor')),
                ('type', models.CharField(choices=[('earn', "Yig'ildi (Vazifa)"), ('spend', 'Saruflandi (Kino)'), ('buy', 'Sotib olindi'), ('bonus', 'Bonus'), ('referral', 'Referal'), ('admin', 'Admin tomonidan')], max_length=50, verbose_name='Turi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sana')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='bot_app.user', verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Tranzaksiya',
                'verbose_name_plural': 'Tranzaksiyalar',
            },
        ),
    ]
