# Generated by Django 5.2.12 on 2026-03-10 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_link',
            field=models.URLField(default='https://t.me/zerikma_filmlar/', help_text='Masalan: https://t.me/zerikma_filmlar/223', verbose_name='Kanal xabari havolasi (Link)'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='message_id',
            field=models.IntegerField(blank=True, help_text="Avtomatik to'ldiriladi", null=True, verbose_name='Xabar ID (Kanalda)'),
        ),
    ]
